config/routes.rb
Spotsor::Application.routes.draw do
  

  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :pins
  resources :contests
  resources :brands
 
 
  get "welcome/index"
   get "users/show"
  
  get "contest/index" => "contests#index"
  get "brand/index" => "brands#index"
  get 'contestsof/:brand_id' => 'contests#contestsof' ,:as => "contestsof"

   root 'pages#index'
   get "forms/new_user_registration" => 'devise#registrations', :as => :forms
   get 'mypins' => 'pins#mypins'
   get 'pinsof/:user_id' => 'pins#pinsof' ,:as => "pinsof"
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/brand.rb
class Brand < ActiveRecord::Base
	mount_uploader :logo, AvatarUploader
	has_many :contests
end

app/models/contest.rb
class Contest < ActiveRecord::Base
	mount_uploader :photo, AvatarUploader
  	validates :photo, presence:true
  	has_many :pins
  	has_many :users, :through => :pins
  	belongs_to :brand

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	
	mount_uploader :photo, AvatarUploader
	validates :photo, presence:true
	validates :description, presence:true
    belongs_to :user
    belongs_to :contest

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :pins
   has_many :contests, :through => :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
before_filter :configure_permitted_parameters, if: :devise_controller?
 
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :phone) }
  end
  
end

app/controllers/brands_controller.rb
class BrandsController <ApplicationController

  	

  def new
	 @brand = Brand.new
  end

  def show
    @brand = Brand.find(params[:id])
    @contests = @brand.contests
    
  end

  def index
    @brands = Brand.all
  end

  def create
    @brand = Brand.new(post_params)

    @brand.save
    redirect_to @brand
  end

  private
  def brand_params
    params.require(:brand).permit( :logo, :name)
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
 
 def contestsof

  @brand_id = params[:brand_id]
  @brand = Brand.find(@brand_id)
  @contests = @brand.contests
   
 end

 def new
   @contest = Contest.new
  end

  def show
    @contest = Contest.find(params[:id])
  end

  def index
    @contests = Contest.all
  end

  def create
    @contest = Contest.new(post_params)

    @contest.save
    redirect_to @contest
  end

  private
  def contest_params
    params.require(:contest).permit( :photo, :description , :minidesc, :fechainicio, :fechatermino, :brand_id )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end 
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user! , except: [ :index, :show]
  
  def mypins 
    @pins = current_user.pins

  end
  def pinsof
    @user_id = params[:user_id]
    @user = User.find(@user_id)
    @pins = @user.pins
    
  end
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new

  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create

    @pin = Pin.new(pin_params)
    @pin.user_id = current_user.id


    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :photo, :name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	#@pins = Pin.where(:user_id => @user.id)
  	@pins = @user.pins
  	
  

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def resource_name
  :user
end

def resource
  @resource ||= User.new
end

def devise_mapping
 @devise_mapping ||= Devise.mappings[:user]
end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :logo %><br>
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<h1>Listing brands</h1>

<br>
<br>
  <div id="container">

    <% @brands.each do |brand| %>
      <div class= "item" style="width:25%">
        <div class="thumbnail">



             <%= brand.name %>





             <%= link_to(image_tag(brand.logo , :class=> 'img-responsive'), brand) %>
            
          </div>
      </div>
    <% end %>


<br>

</div>
<script type="text/javascript">
var $container = $('#container');
// initialize
$container.masonry({
  columnWidth: 200,
  itemSelector: '.item'
});
$(window).load(function(){
var $container = $('#container');
// initialize
$container.masonry({
  columnWidth: 200,
  itemSelector: '.item'
});
})
</script>

app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Logo:</strong>
  <%= @brand.logo %>
</p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>

app/views/contests/_form.html.erb
<%= form_for(@contest) do |f| %>
  <% if @contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest.errors.count, "error") %> prohibited this contest from being saved:</h2>

      <ul>
      <% @contest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group">
  <div class="field">
    <%= f.label :photo , "Foto" %><br>
    <%= f.file_field :photo , :class => 'form-control' %>
  </div>
</div>
  <div class="form-group">
  <div class="field">
    <%= f.label :description , "Descripción" %><br>
    <%= f.text_field :description , :class => 'form-control' %>
  </div>
  </div>
 
<div class="form-group">
  <div class="actions">
    <%= f.submit "Crear", :class => "btn btn-primary"%>
  </div>
</div>
<% end %>

app/views/contests/contestsof.html.erb
<h1>Concursos Disponibles</h1>
 <div id="container">

    <% @contests.each do |contest| %>
       <div class= "row" style="width:25%">
         <div class="thumbnail">

          <%= contest.minidesc %>

           <%= link_to(image_tag(contest.photo , :class=> 'img-responsive'), contest) %>
           
              <div class="buttons" style="margin-top:10px; margin-bottom:10px">
        
           <%= link_to 'Show', contest, :class=>'btn' %>
              </div>
         </div> 
        </div>   
      
    <% end %>




<br>

 </div>
<script type="text/javascript">
var $container = $('#container');
// initialize
$container.masonry({
  columnWidth: 200,
  itemSelector: '.item'
});
$(window).load(function(){
var $container = $('#container');
// initialize
$container.masonry({
  columnWidth: 200,
  itemSelector: '.item'
});
})
</script>

app/views/contests/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">

<h1>Editar Foto</h1>

<%= render 'form' %>
        </div>
    </div>

<%= link_to 'Show', @contest %> |
<%= link_to 'Back', contests_path %>
</div>

app/views/contests/index.html.erb
<div class="container">
<h1>Concursos Disponibles</h1>


    <% @contests.each do |contest| %>
       <div class="col-md-3">
      <div class="thumbnail">
        <%= image_tag(contest.photo , :class=> 'img-responsive')%>
         <div class="buttons" style="margin-top:10px; margin-bottom:10px">
        <%= contest.description %>
        <%= link_to 'Show', contest, :class=>'btn' %>
      </div>
      </div> 
    </div>   
      
    <% end %>

app/views/contests/new.html.erb
<div class="container">
	<div class="col-md-6">


<h1>New contest</h1>

<%= render 'form' %>

<%= link_to 'Back', contests_path %>

app/views/contests/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo:</strong>
  <%= image_tag(@contest.photo, :class=> 'img-responsive') %>
</p>

<p>
  <strong>Description:</strong>
  <%= @contest.description %>
</p>
<p>
  <strong>Término</strong>
  <%= @contest.fechatermino %>
</p>

<%= link_to 'Back', contests_path %>
</div>


<h1>Sube tus fotos!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spotsor.me</title>

   <!-- Latest compiled and minified CSS -->
   
<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
 


<!-- Latest compiled and minified JavaScript -->
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
<script type="text/javascript " src="//cdnjs.cloudflare.com/ajax/libs/masonry/3.1.2/masonry.pkgd.js"></script>
</head>
<body>
 <%= render 'shared/navbar' %>
 <%= yield %>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

</body>
  
</html>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <div class="field">
    <%= f.label :name , "Nombre" %><br>
    <%= f.text_field :name , :class => 'form-control' %>
  </div>
</div>
 <div class="form-group">
  <div class="field">
    <%= f.label :photo , "Foto" %><br>
    <%= f.file_field :photo , :class => 'form-control' %>
  </div>
</div>

 <div class="form-group">
  <div class="field">
    <%= f.label :description , "Descripción" %><br>
    <%= f.text_field :description , :class => 'form-control' %>
  </div>
  </div>
 
<div class="form-group">
  <div class="actions">
    <%= f.submit "Crear", :class => "btn btn-primary"%>
  </div>
</div>
<% end %>

app/views/pins/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">

<h1>Editar Foto</h1>

<%= render 'form' %>
        </div>
    </div>
<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>
  
</div>

app/views/pins/index.html.erb
<h1>Listing pins</h1>




           <% if user_signed_in? %>
              <%= link_to 'Crear nuevo Pin', new_pin_path, :class => 'btn btn-primary' , :style => 'color:white'  %>
            <% end %>
<br>
<br>
  <div id="container">

    <% @pins.each do |pin| %>
      <div class= "item" style="width:25%">
        <div class="thumbnail">



             <%= pin.name %>





             <%= link_to(image_tag(pin.photo , :class=> 'img-responsive'), pin) %>
            
             <%= pin.description %>
                <div class="buttons" style="margin-top:10px; margin-bottom:10px">
              
              <% if user_signed_in? %>
              <%= link_to 'Editar', edit_pin_path(pin), :class => 'btn' %>
              <%= link_to 'Borrar', pin, method: :delete, data: { confirm: 'Estas seguro?' } , :class=> 'btn' %>
          <% end %>
            </div>
          </div>
      </div>
    <% end %>


<br>

</div>
<script type="text/javascript">
var $container = $('#container');
// initialize
$container.masonry({
  columnWidth: 200,
  itemSelector: '.item'
});
$(window).load(function(){
var $container = $('#container');
// initialize
$container.masonry({
  columnWidth: 200,
  itemSelector: '.item'
});
})
</script>

app/views/pins/mypins.html.erb
  <h1>Mis Fotos</h1>
<br>


           <% if user_signed_in? %>
              <%= link_to 'Crear nuevo Pin', new_pin_path, :class => 'btn btn-primary' , :style => 'color:white'  %>
            <% end %>

<br>
<br>
  <div id="container">

    <% @pins.each do |pin| %>
     <div class= "item" style="width:25%">
        <div class="thumbnail">
             <%= pin.name %>
             <%= link_to(image_tag(pin.photo , :class=> 'img-responsive'), pin) %>
            
             <%= pin.description %>
                <div class="buttons" style="margin-top:10px; margin-bottom:10px">
              
              <% if user_signed_in? %>
              <%= link_to 'Editar', edit_pin_path(pin), :class => 'btn' %>
              <%= link_to 'Borrar', pin, method: :delete, data: { confirm: 'Estas seguro?' } , :class=> 'btn' %>
          <% end %>
            </div>
          </div>
      </div>
    <% end %>


<br>

</div>
<script type="text/javascript">
var $container = $('#container');
// initialize
$container.masonry({
  columnWidth: 200,
  itemSelector: '.item'
});
$(window).load(function(){
var $container = $('#container');
// initialize
$container.masonry({
  columnWidth: 200,
  itemSelector: '.item'
});
})
</script>

app/views/pins/new.html.erb
<div class="container">
	<div class="col-md-6">
	<h1>Nuevo pin</h1>

	<%= render 'form' %>

	
	</div>
	<p> <%= link_to 'Back', pins_path %> </p>
</div>

app/views/pins/pinsof.html.erb
<h1>Listing pins</h1>




           <% if user_signed_in? %>
              <%= link_to 'Crear nuevo Pin', new_pin_path, :class => 'btn btn-primary' , :style => 'color:white'  %>
            <% end %>
<br>
<br>
  <div id="container">

    <% @pins.each do |pin| %>
      <div class= "item" style="width:25%">
        <div class="thumbnail">



             <%= pin.name %>





             <%= link_to(image_tag(pin.photo , :class=> 'img-responsive'), pin) %>
            
             <%= pin.description %>
                <div class="buttons" style="margin-top:10px; margin-bottom:10px">
              
              <% if user_signed_in? %>
              <%= link_to 'Editar', edit_pin_path(pin), :class => 'btn' %>
              <%= link_to 'Borrar', pin, method: :delete, data: { confirm: 'Estas seguro?' } , :class=> 'btn' %>
          <% end %>
            </div>
          </div>
      </div>
    <% end %>


<br>
</div>
<script type="text/javascript">
var $container = $('#container');
// initialize
$container.masonry({
  columnWidth: 200,
  itemSelector: '.item'
});
$(window).load(function(){
var $container = $('#container');
// initialize
$container.masonry({
  columnWidth: 200,
  itemSelector: '.item'
});
})
</script>

app/views/pins/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @pin.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag(@pin.photo, :class=> 'img-responsive') %>
</p>
<% if user_signed_in? %>
<%= link_to 'Edit', edit_pin_path(@pin) %> |
<% end %>
<%= link_to 'Back', pins_path %>
</div>

<%= link_to "Mas fotos del usuario", pinsof_path(@pin.user.id) %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation" style="margin-bottom:10px">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand " href="<%= root_path%>">Spotsor.me</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav ">
        <li class="dropdown">
        <a id="drop4" role="button" data-toggle="dropdown" href="<%= pins_path %>">Concursos <span class="caret"></span></a>
        <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
          <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= contestsof_path('1')%>"> Spotsorme</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= contestsof_path('2')%>">Vans</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= contestsof_path('3')%>">DC Shoes</a></li>
          <li role="presentation" class="divider"></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="<%= contests_path %>">Todos los Concursos</a></li>
        </ul>
      </li>
        
        <li > <a href="<%= mypins_path %>"> Mi Perfil</a></li>
        <li > <a href="#"> Ganadores</a></li>
      </ul>
       
          
            
            <ul class="nav navbar-nav navbar-right">
              <% if current_user.nil? %>

               <a class="btn" data-toggle="modal" href="#myModal" >Ingreso Usuarios</a>
              <div class="modal" id="myModal">
                 <%= render :template => "devise/sessions/new" %>
              </div>
           
               <a class="btn" data-toggle="modal" href="#myModal2" >Registrarse</a>
              <div class="modal" id="myModal2">
                 <%= render :template => "devise/registrations/new" %>
              </div>

             
            <% else %>
            <li> <a href="#">Hola <%= current_user.email %> </a></li>
            <li></li>
            <li><a href="<%= destroy_user_session_path %>" data-method="delete">Salir</a></li>
            <% end %>


          </ul>
           
          
      
    </div><!-- /.navbar-collapse -->
</nav>


      
    

app/views/users/show.html.erb
<div class="container">



           <% if user_signed_in? %>
              <%= link_to 'Crear nuevo Pin', new_pin_path, :class => 'btn btn-primary' , :style => 'color:white'  %>
            <% end %>

  <h1>Listing pins</h1>
<br>
<br>
    <% @pins.each do |pin| %>
      <div class="col-md-3">
        <div class="thumbnail">
             <%= pin.name %>
             <%= link_to(image_tag(pin.photo , :class=> 'img-responsive'), pin) %>
            
             <%= pin.description %>
                <div class="buttons" style="margin-top:10px; margin-bottom:10px">
              
              <% if user_signed_in? %>
              <%= link_to 'Editar', edit_pin_path(pin), :class => 'btn' %>
              <%= link_to 'Borrar', pin, method: :delete, data: { confirm: 'Estas seguro?' } , :class=> 'btn' %>
          <% end %>
            </div>
          </div>
      </div>
    <% end %>


<br>

</div>